version: '3.8'

services:
  converter:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-serverless-converter-dev-uploads}
      - TMP_DIR=/tmp
    volumes:
      - ./:/app
      - /app/node_modules
      - tmp_data:/tmp

volumes:
  tmp_data: