service: serverless-converter
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 2048 # Increased for FFmpeg/LibreOffice tasks
  timeout: 900 # 15 minutes max timeout for longer conversions
  environment:
    AWS_BUCKET_NAME: ${self:custom.bucketName}
    TMP_DIR: /tmp
    JOBS_TABLE_NAME: ${self:service}-${self:provider.stage}-jobs
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::${self:custom.bucketName}/*
        # Least privilege principle - only allow necessary actions
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
          Resource: arn:aws:dynamodb:*:*:table/${self:service}-${self:provider.stage}-jobs
        - Effect: Allow
          Action: ssm:GetParameter
          Resource: arn:aws:ssm:*:*:parameter/serverless-converter/*

custom:
  bucketName: ${self:service}-${self:provider.stage}-uploads
  # Add authorizer configuration
  authorizers:
    apiAuthorizer:
      type: token
      identitySource: method.request.header.Authorization

functions:
  apiAuthorizer:
    handler: functions/apiAuthorizer.handler
    environment:
      JWT_SECRET: ${env:JWT_SECRET, ''}
    # Add rate limiting to prevent abuse
    events:
      - http:
          path: auth
          method: post
          cors: true
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  convertHeicToJpg:
    handler: functions/convertHeicToJpg.handler
    events:
      - http:
          path: convert/heic-to-jpg
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  convertImageToPdf:
    handler: functions/convertImageToPdf.handler
    events:
      - http:
          path: convert/image-to-pdf
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  convertVideo:
    handler: functions/convertVideo.handler
    events:
      - http:
          path: convert/video
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  convertVideoToMp3:
    handler: functions/convertVideoToMp3.handler
    events:
      - http:
          path: convert/video-to-mp3
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  extractPdfPages:
    handler: functions/extractPdfPages.handler
    events:
      - http:
          path: convert/extract-pdf-pages
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  removePdfPages:
    handler: functions/removePdfPages.handler
    events:
      - http:
          path: convert/remove-pdf-pages
          method: post
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 10
            rateLimit: 5
  
  download:
    handler: functions/download.handler
    events:
      - http:
          path: download
          method: get
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 20
            rateLimit: 10
  
  progress:
    handler: functions/progress.handler
    events:
      - http:
          path: progress/{jobId}
          method: get
          cors: true
          authorizer:
            name: apiAuthorizer
            type: token
          throttling:
            burstLimit: 20
            rateLimit: 10

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['Content-Type', 'Authorization', 'X-Amz-Date', 'X-Api-Key']
              AllowedMethods: [GET, PUT, POST, DELETE]
              # Replace with your specific frontend domains in production
              AllowedOrigins: ['http://localhost:3000', 'https://your-production-domain.com']
              MaxAge: 3000
        LifecycleConfiguration:
          Rules:
            - Id: DeleteAfter7Days
              Status: Enabled
              ExpirationInDays: 7
    
    ConversionJobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-jobs
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true